"use server";
import { redirect } from "next/navigation"; import { revalidatePath } from "next/cache"; import { createClient } from "@/lib/supabase/server";
export async function login(formData:FormData){const supabase=await createClient();const {error}=await supabase.auth.signInWithPassword({email:String(formData.get('email')||''),password:String(formData.get('password')||'')});if(error)redirect('/admin/login?error=1');redirect('/admin')}
export async function logout(){const supabase=await createClient();await supabase.auth.signOut();redirect('/')}
export async function saveSettings(formData:FormData){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');await supabase.from('wedding_settings').upsert({id:1,rsvp_open:formData.get('rsvp_open')==='on',rsvp_deadline:formData.get('rsvp_deadline'),show_faq:formData.get('show_faq')==='on',show_dress_code:formData.get('show_dress_code')==='on',show_playlist:formData.get('show_playlist')==='on',show_programme:formData.get('show_programme')==='on'});revalidatePath('/admin/settings')}
async function requireAdmin(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');return supabase}
export async function createInvitation(formData:FormData){const supabase=await requireAdmin();const names=String(formData.get('guest_names')||'').split('\n').map(x=>x.trim()).filter(Boolean).slice(0,4);if(!names.length)return;const supplied=String(formData.get('code')||'').trim().toUpperCase();const code=supplied||`ANA-NUNO-2027-${crypto.randomUUID().slice(0,4).toUpperCase()}`;await supabase.rpc('admin_create_invitation',{invitation_code:code,invitation_language:formData.get('language')==='en'?'en':'pt',guest_names:names});revalidatePath('/admin');revalidatePath('/admin/invitations');revalidatePath('/admin/guests')}
export async function updateInvitationStatus(formData:FormData){const supabase=await requireAdmin();const id=String(formData.get('id')||'');const status=String(formData.get('status')||'');if(!['active','used','disabled'].includes(status))return;await supabase.from('invitations').update({status}).eq('id',id);revalidatePath('/admin/invitations')}
export async function updateGuest(formData:FormData){const supabase=await requireAdmin();const id=String(formData.get('id')||'');const category=String(formData.get('category')||'adult');const attendance=String(formData.get('attendance')||'pending');if(!['adult','child','baby'].includes(category)||!['pending','accepted','declined'].includes(attendance))return;await supabase.from('guests').update({category,attendance,dietary_restrictions:String(formData.get('dietary_restrictions')||'').trim()||null,notes:String(formData.get('notes')||'').trim()||null,updated_at:new Date().toISOString()}).eq('id',id);revalidatePath('/admin');revalidatePath('/admin/guests')}
