"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { parseGuestImport } from "@/lib/guest-import";

type ActionError={message:string}|null;
const value=(formData:FormData,key:string)=>String(formData.get(key)||'').trim();
const optional=(formData:FormData,key:string)=>value(formData,key)||null;
const finish=(path:string,error:ActionError,success:string):never=>redirect(`${path}?${error?'error':'success'}=${encodeURIComponent(error?.message??success)}&notice=${Date.now()}`);

async function requireAdmin(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');const {data:isAdmin}=await supabase.rpc('is_admin');if(!isAdmin)redirect('/admin/login?unauthorized=1');return supabase}

export async function login(formData:FormData){const supabase=await createClient();const {error}=await supabase.auth.signInWithPassword({email:value(formData,'email'),password:value(formData,'password')});if(error)redirect('/admin/login?error=1');const {data:isAdmin}=await supabase.rpc('is_admin');if(!isAdmin){await supabase.auth.signOut();redirect('/admin/login?unauthorized=1')}redirect('/admin')}
export async function logout(){const supabase=await createClient();await supabase.auth.signOut();redirect('/')}

export async function saveSettings(formData:FormData){const supabase=await requireAdmin();const playlistDisplayMode=value(formData,'playlist_display_mode')==='cloud'?'cloud':'list';const {error}=await supabase.from('wedding_settings').upsert({id:1,rsvp_open:formData.get('rsvp_open')==='on',rsvp_deadline:value(formData,'rsvp_deadline'),show_faq:formData.get('show_faq')==='on',show_dress_code:formData.get('show_dress_code')==='on',show_playlist:formData.get('show_playlist')==='on',show_public_playlist:formData.get('show_public_playlist')==='on',playlist_display_mode:playlistDisplayMode,show_programme:formData.get('show_programme')==='on'});revalidatePath('/');revalidatePath('/rsvp');revalidatePath('/admin/settings');finish('/admin/settings',error,'Settings saved.')}

export async function createInvitation(formData:FormData){const supabase=await requireAdmin();const names=value(formData,'guest_names').split('\n').map(x=>x.trim()).filter(Boolean).slice(0,5);if(!names.length)finish('/admin/invitations',{message:'Add at least one guest name.'},'');const supplied=value(formData,'code').toUpperCase();const code=supplied||`ANA-NUNO-2027-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const {error}=await supabase.rpc('admin_create_invitation',{invitation_code:code,invitation_language:value(formData,'language')==='en'?'en':'pt',guest_names:names});revalidatePath('/admin');revalidatePath('/admin/invitations');revalidatePath('/admin/guests');finish('/admin/invitations',error,error?'':'Invitation created.')}
export async function importInvitations(formData:FormData){const supabase=await requireAdmin();const file=formData.get('file');if(!(file instanceof File))return finish('/admin/invitations',{message:'Choose a CSV or XLSX file.'},'');let rows:Awaited<ReturnType<typeof parseGuestImport>>;try{rows=await parseGuestImport(file)}catch(error){return finish('/admin/invitations',{message:error instanceof Error?error.message:'Unable to read the import file.'},'')}const {data,error}=await supabase.rpc('admin_import_invitations',{p_rows:rows});revalidatePath('/admin');revalidatePath('/admin/invitations');revalidatePath('/admin/guests');finish('/admin/invitations',error,`${data??rows.length} invitations imported with unique codes.`)}
export async function updateInvitationStatus(formData:FormData){const supabase=await requireAdmin();const status=value(formData,'status');if(!['active','used','disabled'].includes(status))finish('/admin/invitations',{message:'Invalid invitation status.'},'');const {error}=await supabase.from('invitations').update({status}).eq('id',value(formData,'id'));revalidatePath('/admin/invitations');finish('/admin/invitations',error,'Invitation status saved.')}

const guestReturnPath=(formData:FormData)=>value(formData,'return_to')==='/admin/invitations'?'/admin/invitations':'/admin/guests';
export async function updateGuest(formData:FormData){const supabase=await requireAdmin();const returnPath=guestReturnPath(formData);const category=value(formData,'category')||'adult';const attendance=value(formData,'attendance')||'pending';const name=value(formData,'name');if(!name)finish(returnPath,{message:'Guest name is required.'},'');if(!['adult','child','baby'].includes(category)||!['pending','accepted','declined'].includes(attendance))finish(returnPath,{message:'Invalid guest details.'},'');const {error}=await supabase.from('guests').update({name:name.slice(0,150),category,attendance,dietary_restrictions:optional(formData,'dietary_restrictions'),notes:optional(formData,'notes'),updated_at:new Date().toISOString()}).eq('id',value(formData,'id'));revalidatePath('/admin');revalidatePath('/admin/invitations');revalidatePath('/admin/guests');revalidatePath('/rsvp');finish(returnPath,error,'Guest saved.')}
export async function addGuest(formData:FormData){const supabase=await requireAdmin();const returnPath=guestReturnPath(formData);const {error}=await supabase.rpc('admin_add_guest',{p_invitation_id:value(formData,'invitation_id'),p_guest_name:value(formData,'name'),p_category:value(formData,'category')||'adult'});revalidatePath('/admin');revalidatePath('/admin/invitations');revalidatePath('/admin/guests');revalidatePath('/rsvp');finish(returnPath,error,'Guest added.')}
export async function removeGuest(formData:FormData){const supabase=await requireAdmin();const returnPath=guestReturnPath(formData);const {error}=await supabase.rpc('admin_remove_guest',{p_guest_id:value(formData,'id')});revalidatePath('/admin');revalidatePath('/admin/invitations');revalidatePath('/admin/guests');revalidatePath('/rsvp');finish(returnPath,error,'Guest removed.')}

export async function saveMusicSuggestion(formData:FormData){const supabase=await requireAdmin();const id=value(formData,'id');const song=value(formData,'song').slice(0,150);const artist=value(formData,'artist').slice(0,150);if(!song||!artist)finish('/admin/playlist',{message:'Song and artist are required.'},'');const {error}=id?await supabase.from('music_suggestions').update({song,artist}).eq('id',id):await supabase.from('music_suggestions').insert({song,artist});revalidatePath('/');revalidatePath('/admin/playlist');finish('/admin/playlist',error,id?'Music suggestion saved.':'Music suggestion added.')}
export async function deleteMusicSuggestion(formData:FormData){const supabase=await requireAdmin();const {error}=await supabase.from('music_suggestions').delete().eq('id',value(formData,'id'));revalidatePath('/');revalidatePath('/admin/playlist');finish('/admin/playlist',error,'Music suggestion deleted.')}

export async function saveContent(formData:FormData){const supabase=await requireAdmin();const fields=['city_pt','city_en','story_pt','story_en','dress_title_pt','dress_title_en','dress_text_pt','dress_text_en','rsvp_intro_pt','rsvp_intro_en','playlist_prompt_pt','playlist_prompt_en','message_prompt_pt','message_prompt_en','footer_pt','footer_en'];const content=Object.fromEntries(fields.map(key=>[key,value(formData,key)]));const {error}=await supabase.from('site_content').upsert({id:1,...content,updated_at:new Date().toISOString()});revalidatePath('/');revalidatePath('/rsvp');revalidatePath('/admin/content');finish('/admin/content',error,'General information saved.')}
export async function saveEvent(formData:FormData){const supabase=await requireAdmin();const id=value(formData,'id');const venuePt=optional(formData,'venue_pt');const venueEn=optional(formData,'venue_en');const addressPt=optional(formData,'address_pt');const addressEn=optional(formData,'address_en');const event={title_pt:value(formData,'title_pt'),title_en:value(formData,'title_en'),description_pt:optional(formData,'description_pt'),description_en:optional(formData,'description_en'),event_date:value(formData,'event_date'),start_time:optional(formData,'start_time'),end_time:optional(formData,'end_time'),venue:venuePt,venue_pt:venuePt,venue_en:venueEn,address:addressPt,address_pt:addressPt,address_en:addressEn,maps_url:optional(formData,'maps_url'),position:Number(value(formData,'position')||0),is_active:formData.get('is_active')==='on',updated_at:new Date().toISOString()};const {error}=id?await supabase.from('event_details').update(event).eq('id',id):await supabase.from('event_details').insert(event);revalidatePath('/');revalidatePath('/admin/content');finish('/admin/content',error,id?'Event saved.':'Event created.')}
export async function deleteEvent(formData:FormData){const supabase=await requireAdmin();const {error}=await supabase.from('event_details').delete().eq('id',value(formData,'id'));revalidatePath('/');revalidatePath('/admin/content');finish('/admin/content',error,'Event deleted.')}

export async function saveFaq(formData:FormData){const supabase=await requireAdmin();const id=value(formData,'id');const faq={question_pt:value(formData,'question_pt'),question_en:value(formData,'question_en'),answer_pt:value(formData,'answer_pt'),answer_en:value(formData,'answer_en'),position:Number(value(formData,'position')||0),is_active:formData.get('is_active')==='on',updated_at:new Date().toISOString()};const {error}=id?await supabase.from('faqs').update(faq).eq('id',id):await supabase.from('faqs').insert(faq);revalidatePath('/');revalidatePath('/admin/content');finish('/admin/content',error,id?'FAQ saved.':'FAQ created.')}
export async function deleteFaq(formData:FormData){const supabase=await requireAdmin();const {error}=await supabase.from('faqs').delete().eq('id',value(formData,'id'));revalidatePath('/');revalidatePath('/admin/content');finish('/admin/content',error,'FAQ deleted.')}

export async function saveQuestion(formData:FormData){const supabase=await requireAdmin();const id=value(formData,'id');const pt=value(formData,'options_pt').split('\n').map(x=>x.trim()).filter(Boolean);const en=value(formData,'options_en').split('\n').map(x=>x.trim()).filter(Boolean);const optionCount=Math.max(pt.length,en.length);const options=Array.from({length:optionCount},(_,index)=>({label_pt:pt[index]||en[index],label_en:en[index]||pt[index],value:`option_${index+1}`}));const questionType=value(formData,'question_type');if(options.length&&!['single_choice','multiple_choice'].includes(questionType))finish('/admin/questions',{message:'Select One choice or Multiple choices to display the options.'},'');const question={label_pt:value(formData,'label_pt'),label_en:value(formData,'label_en'),help_pt:optional(formData,'help_pt'),help_en:optional(formData,'help_en'),question_type:questionType,scope:value(formData,'scope'),options,required:formData.get('required')==='on',is_active:formData.get('is_active')==='on',position:Number(value(formData,'position')||0),updated_at:new Date().toISOString()};const {error}=id?await supabase.from('rsvp_questions').update(question).eq('id',id):await supabase.from('rsvp_questions').insert(question);revalidatePath('/rsvp');revalidatePath('/admin/questions');finish('/admin/questions',error,id?'Question saved.':'Question created.')}
export async function deleteQuestion(formData:FormData){const supabase=await requireAdmin();const {error}=await supabase.from('rsvp_questions').delete().eq('id',value(formData,'id'));revalidatePath('/rsvp');revalidatePath('/admin/questions');finish('/admin/questions',error,'Question deleted.')}
