import { createClient } from "@/lib/supabase/server";
import { deleteEvent,deleteFaq,saveContent,saveEvent,saveFaq } from "../../actions";

const fieldClass="text-[10px] uppercase tracking-widest";
const contentFields=[
  ['city','City / location','Localidade'],['story','Story introduction','Introdução'],['dress_title','Dress-code title','Título do dress code'],['dress_text','Dress-code details','Detalhes do dress code'],['rsvp_intro','RSVP introduction','Introdução ao RSVP'],['playlist_prompt','Playlist question','Pergunta da playlist'],['message_prompt','Message question','Pergunta da mensagem'],['footer','Footer message','Mensagem final']
];
type Content=Record<string,string>;
type EventRow={id:string;title_pt:string;title_en:string;description_pt:string|null;description_en:string|null;event_date:string;start_time:string|null;end_time:string|null;venue:string|null;address:string|null;maps_url:string|null;position:number;is_active:boolean};
type FaqRow={id:string;question_pt:string;question_en:string;answer_pt:string;answer_en:string;position:number;is_active:boolean};

export default async function ContentPage(){
  const s=await createClient();
  const [{data:content},{data:events},{data:faqs}]=await Promise.all([
    s.from('site_content').select('*').eq('id',1).maybeSingle(),
    s.from('event_details').select('*').order('position'),
    s.from('faqs').select('*').order('position')
  ]);
  const values=(content??{}) as Content;
  return <><p className="eyebrow">Website editor</p><h1 className="font-editorial my-6 text-6xl">Content</h1><p className="mb-10 max-w-2xl text-sm leading-6 opacity-70">Everything shown to guests can be maintained here in Portuguese and English. Save each section independently.</p>
    <section className="mb-12 bg-[#f8f4ed] p-6"><h2 className="font-editorial text-4xl">General information</h2><form action={saveContent} className="mt-7 space-y-8">{contentFields.map(([key,enLabel,ptLabel])=><fieldset className="grid gap-5 border-t border-black/10 pt-5 sm:grid-cols-2" key={key}><legend className="mb-2 text-sm font-medium">{enLabel}</legend><label className={fieldClass}>{ptLabel} · PT<textarea className="field min-h-20" name={`${key}_pt`} defaultValue={values[`${key}_pt`]??''} required/></label><label className={fieldClass}>{enLabel} · EN<textarea className="field min-h-20" name={`${key}_en`} defaultValue={values[`${key}_en`]??''} required/></label></fieldset>)}<button className="button">Save general information</button></form></section>
    <section className="mb-12"><p className="eyebrow">Programme & locations</p><h2 className="font-editorial my-5 text-4xl">Events</h2><div className="grid gap-5">{[...((events??[]) as EventRow[]),null].map((event,index)=><details className="bg-[#f8f4ed] p-6" key={event?.id??'new-event'} open={!event}><summary className="cursor-pointer font-editorial text-3xl">{event?`${event.title_pt} / ${event.title_en}`:'Add event'} <span className="float-right">{event?'Edit':'+'}</span></summary><form action={saveEvent} className="mt-6 grid gap-5 sm:grid-cols-2"><input type="hidden" name="id" value={event?.id??''}/><label className={fieldClass}>Título · PT<input className="field" name="title_pt" defaultValue={event?.title_pt??''} required/></label><label className={fieldClass}>Title · EN<input className="field" name="title_en" defaultValue={event?.title_en??''} required/></label><label className={fieldClass}>Descrição · PT<textarea className="field" name="description_pt" defaultValue={event?.description_pt??''}/></label><label className={fieldClass}>Description · EN<textarea className="field" name="description_en" defaultValue={event?.description_en??''}/></label><label className={fieldClass}>Date<input className="field" type="date" name="event_date" defaultValue={event?.event_date??'2027-04-24'} required/></label><div className="grid grid-cols-2 gap-4"><label className={fieldClass}>Start<input className="field" type="time" name="start_time" defaultValue={event?.start_time?.slice(0,5)??''}/></label><label className={fieldClass}>End<input className="field" type="time" name="end_time" defaultValue={event?.end_time?.slice(0,5)??''}/></label></div><label className={fieldClass}>Venue<input className="field" name="venue" defaultValue={event?.venue??''}/></label><label className={fieldClass}>Address<input className="field" name="address" defaultValue={event?.address??''}/></label><label className={fieldClass}>Google Maps URL<input className="field" type="url" name="maps_url" defaultValue={event?.maps_url??''}/></label><label className={fieldClass}>Order<input className="field" type="number" name="position" defaultValue={event?.position??index+1}/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="is_active" defaultChecked={event?.is_active??true}/> Visible to guests</label><div className="flex flex-wrap gap-3 sm:col-span-2"><button className="button">{event?'Save event':'Create event'}</button>{event&&<button className="button text-red-800" formAction={deleteEvent}>Delete</button>}</div></form></details>)}</div></section>
    <section><p className="eyebrow">Useful information</p><h2 className="font-editorial my-5 text-4xl">Frequently asked questions</h2><div className="grid gap-5">{[...((faqs??[]) as FaqRow[]),null].map((faq,index)=><details className="bg-[#f8f4ed] p-6" key={faq?.id??'new-faq'} open={!faq}><summary className="cursor-pointer font-editorial text-2xl">{faq?.question_en??'Add FAQ'} <span className="float-right">{faq?'Edit':'+'}</span></summary><form action={saveFaq} className="mt-6 grid gap-5 sm:grid-cols-2"><input type="hidden" name="id" value={faq?.id??''}/><label className={fieldClass}>Pergunta · PT<input className="field" name="question_pt" defaultValue={faq?.question_pt??''} required/></label><label className={fieldClass}>Question · EN<input className="field" name="question_en" defaultValue={faq?.question_en??''} required/></label><label className={fieldClass}>Resposta · PT<textarea className="field min-h-24" name="answer_pt" defaultValue={faq?.answer_pt??''} required/></label><label className={fieldClass}>Answer · EN<textarea className="field min-h-24" name="answer_en" defaultValue={faq?.answer_en??''} required/></label><label className={fieldClass}>Order<input className="field" type="number" name="position" defaultValue={faq?.position??index+1}/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="is_active" defaultChecked={faq?.is_active??true}/> Visible to guests</label><div className="flex flex-wrap gap-3 sm:col-span-2"><button className="button">{faq?'Save FAQ':'Create FAQ'}</button>{faq&&<button className="button text-red-800" formAction={deleteFaq}>Delete</button>}</div></form></details>)}</div></section>
  </>;
}
