import { Suspense } from "react";
import { Countdown } from "@/components/countdown";
import { LanguageSwitcher } from "@/components/language-switcher";
import { RsvpEntry } from "@/components/rsvp-entry";
import { copy } from "@/lib/content";
import { createClient } from "@/lib/supabase/server";
import type { Language } from "@/types";

type SiteContent=Record<string,string>;
type EventDetail={id:string;title_pt:string;title_en:string;description_pt:string|null;description_en:string|null;event_date:string;start_time:string|null;end_time:string|null;venue:string|null;address:string|null;maps_url:string|null};
type Faq={id:string;question_pt:string;question_en:string;answer_pt:string;answer_en:string};

export default async function Home({searchParams}:{searchParams:Promise<{lang?:string}>}){
  const {lang:raw}=await searchParams;const lang:Language=raw==='en'?'en':'pt';const c=copy[lang];const s=await createClient();
  const [{data:content},{data:events},{data:faqs},{data:settings}]=await Promise.all([s.from('site_content').select('*').eq('id',1).maybeSingle(),s.from('event_details').select('*').eq('is_active',true).order('position'),s.from('faqs').select('*').eq('is_active',true).order('position'),s.from('wedding_settings').select('*').eq('id',1).maybeSingle()]);
  const dynamic=(content??{}) as SiteContent;const programme=(events??[]) as EventDetail[];const faqItems=(faqs??[]) as Faq[];const localized=(key:string,fallback:string)=>dynamic[`${key}_${lang}`]||fallback;const firstEvent=programme[0];const weddingDate=firstEvent?.event_date??'2027-04-24';const countdownDate=`${weddingDate}T${firstEvent?.start_time?.slice(0,8)??'14:30:00'}+01:00`;const displayDate=new Intl.DateTimeFormat(lang==='pt'?'pt-PT':'en-GB',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${weddingDate}T12:00:00`));
  return <main>
    <header className="fixed inset-x-0 top-0 z-20 flex items-center justify-between px-5 py-5 mix-blend-multiply sm:px-10"><a href="#top" className="font-editorial text-xl">A <span className="text-[#b65f41]">×</span> N</a><nav className="hidden gap-7 lg:flex">{c.nav.map(([n,h]:string[])=><a className="eyebrow hover:opacity-50" href={h} key={h}>{n}</a>)}</nav><Suspense><LanguageSwitcher label={c.language}/></Suspense></header>
    <section id="top" className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 text-center"><div className="absolute left-[8%] top-[18%] h-28 w-28 rounded-full border border-[#b65f41]/30 sm:h-48 sm:w-48"/><div className="absolute bottom-[12%] right-[5%] h-48 w-32 rotate-12 rounded-[50%] bg-[#d9c7ad]/45 sm:h-72 sm:w-48"/><div className="reveal relative"><p className="eyebrow">Together · {displayDate}</p><h1 className="font-editorial my-8 text-[20vw] font-normal leading-[.72] tracking-[-.07em] sm:text-[12rem]">Ana<span className="mx-[.12em] text-[#b65f41]">&</span>Nuno</h1><p className="eyebrow">{localized('city',c.city)}</p><a href="#story" className="mt-16 inline-block text-2xl" aria-label="Scroll">↓</a></div></section>
    <section id="story" className="grid min-h-[80vh] place-items-center bg-[#392f29] px-6 py-28 text-[#f4efe7]"><div className="max-w-4xl text-center"><p className="eyebrow">01 · {lang==='pt'?'Nós':'Us'}</p><h2 className="font-editorial mt-10 text-5xl leading-tight sm:text-8xl">{localized('story',c.intro)}</h2></div></section>
    <section className="px-6 py-28 text-center sm:py-40"><p className="eyebrow">{c.countdown}</p><Countdown labels={[c.days,c.hours,c.minutes,c.seconds]} date={countdownDate}/></section>
    {(settings?.show_programme??true)&&<section id="programme" className="grid bg-[#d9c7ad] px-6 py-28 sm:grid-cols-2 sm:px-16 sm:py-40"><div><p className="eyebrow">02 · {c.programme}</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{weddingDate.split('-').reverse().join('.')}</h2></div><div className="mt-16 space-y-10 sm:mt-0">{programme.map(event=><div className="border-t border-current pt-4" key={event.id}>{event.start_time&&<span className="eyebrow">{event.start_time.slice(0,5)}{event.end_time&&` — ${event.end_time.slice(0,5)}`}</span>}<h3 className="font-editorial mt-3 text-4xl">{lang==='pt'?event.title_pt:event.title_en}</h3>{(lang==='pt'?event.description_pt:event.description_en)&&<p className="mt-2 text-sm opacity-75">{lang==='pt'?event.description_pt:event.description_en}</p>}{event.venue&&<p className="mt-2 text-sm">{event.venue}</p>}{event.address&&<p className="mt-1 text-sm opacity-65">{event.address}</p>}{event.maps_url&&<a className="eyebrow mt-4 inline-block underline" href={event.maps_url} target="_blank" rel="noreferrer">{lang==='pt'?'Ver mapa ↗':'View map ↗'}</a>}</div>)}</div></section>}
    {(settings?.show_dress_code??true)&&<section id="dress-code" className="grid min-h-[75vh] place-items-center px-6 py-28 text-center"><div className="max-w-2xl"><p className="eyebrow">03 · {c.dress}</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{localized('dress_title',c.dressTitle)}</h2><p className="mx-auto mt-8 max-w-lg leading-7 opacity-75">{localized('dress_text',c.dressText)}</p><div className="mt-12 flex justify-center gap-3">{['#ede4d5','#cbb89d','#b65f41','#7c5947','#5d6250'].map(x=><span key={x} className="h-11 w-11 rounded-full" style={{background:x}}/>)}</div></div></section>}
    {(settings?.show_faq??true)&&<section id="faq" className="bg-[#5d6250] px-6 py-28 text-[#fffaf3] sm:px-16"><div className="mx-auto max-w-5xl"><p className="eyebrow">04 · FAQ</p><h2 className="font-editorial my-10 text-6xl sm:text-8xl">{c.faq}</h2>{(faqItems.length?faqItems:c.faqs.map(([question,answer],index)=>({id:String(index),question_pt:question,question_en:question,answer_pt:answer,answer_en:answer}))).map(item=><details className="border-t border-white/35 py-6" key={item.id}><summary className="cursor-pointer list-none font-editorial text-3xl">{lang==='pt'?item.question_pt:item.question_en}<span className="float-right">+</span></summary><p className="mt-4 max-w-xl text-sm leading-6 opacity-75">{lang==='pt'?item.answer_pt:item.answer_en}</p></details>)}</div></section>}
    <section id="rsvp" className="px-6 py-32 text-center sm:py-44"><p className="eyebrow">05 · RSVP</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{c.rsvp}</h2><p className="mt-5 text-sm opacity-70">{localized('rsvp_intro',c.rsvpText)}</p>{(settings?.rsvp_open??true)?<RsvpEntry lang={lang}/>:<p className="mt-8 text-sm">{lang==='pt'?'As respostas estão encerradas.':'Responses are now closed.'}</p>}</section>
    <footer className="bg-[#b65f41] px-6 py-20 text-center text-[#fffaf3]"><p className="font-editorial text-4xl sm:text-6xl">{localized('footer',c.footer)}</p><p className="eyebrow mt-10">Ana & Nuno · 2027</p></footer>
  </main>;
}
