import { Suspense } from "react";
import { Countdown } from "@/components/countdown";
import { LanguageSwitcher } from "@/components/language-switcher";
import { RsvpEntry } from "@/components/rsvp-entry";
import { copy } from "@/lib/content";
import { createClient } from "@/lib/supabase/server";
import type { Language } from "@/types";

type SiteContent=Record<string,string>;
type EventDetail={id:string;title_pt:string;title_en:string;description_pt:string|null;description_en:string|null;event_date:string;start_time:string|null;end_time:string|null;venue:string|null;address:string|null;maps_url:string|null};
type Faq={id:string;question_pt:string;question_en:string;answer_pt:string;answer_en:string};
type MusicSuggestion={song:string;artist:string};

export default async function Home({searchParams}:{searchParams:Promise<{lang?:string}>}){
  const {lang:raw}=await searchParams;const lang:Language=raw==='en'?'en':'pt';const c=copy[lang];const s=await createClient();
  const [{data:content},{data:events},{data:faqs},{data:settings},{data:musicSuggestions}]=await Promise.all([s.from('site_content').select('*').eq('id',1).maybeSingle(),s.from('event_details').select('*').eq('is_active',true).order('position'),s.from('faqs').select('*').eq('is_active',true).order('position'),s.from('wedding_settings').select('*').eq('id',1).maybeSingle(),s.rpc('get_public_music_suggestions')]);
  const dynamic=(content??{}) as SiteContent;const programme=(events??[]) as EventDetail[];const faqItems=(faqs??[]) as Faq[];const publicPlaylist=(musicSuggestions??[]) as MusicSuggestion[];const cloudPlaylist=Array.from(publicPlaylist.reduce<Map<string,MusicSuggestion&{count:number}>>((items,item)=>{const key=`${item.song.trim().toLocaleLowerCase()}|${item.artist.trim().toLocaleLowerCase()}`;const existing=items.get(key);if(existing)existing.count+=1;else items.set(key,{...item,count:1});return items},new Map()).values());const playlistDisplayMode=settings?.playlist_display_mode==='cloud'?'cloud':'list';const localized=(key:string,fallback:string)=>dynamic[`${key}_${lang}`]||fallback;const firstEvent=programme[0];const weddingDate=firstEvent?.event_date??'2027-04-24';const countdownDate=`${weddingDate}T${firstEvent?.start_time?.slice(0,8)??'14:30:00'}+01:00`;const displayDate=new Intl.DateTimeFormat(lang==='pt'?'pt-PT':'en-GB',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${weddingDate}T12:00:00`));
  return <main>
    <header className="fixed inset-x-0 top-0 z-20 flex items-center justify-between border-b border-[#392f29]/10 bg-[#f4efe7] px-5 py-5 sm:px-10"><a href="#top" className="font-editorial text-xl">A <span className="text-[#b65f41]">+</span> N</a><nav className="hidden gap-7 lg:flex">{c.nav.map(([n,h]:string[])=><a className="eyebrow hover:opacity-50" href={h} key={h}>{n}</a>)}</nav><div className="flex items-center gap-5"><a href="/admin" className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-current/40 transition hover:bg-[#392f29] hover:text-[#f4efe7]" aria-label={lang==='pt'?'Acesso de administração':'Admin sign in'} title={lang==='pt'?'Acesso de administração':'Admin sign in'}><svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4 fill-none stroke-current" strokeWidth="1.7"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8.5 10V7.5a3.5 3.5 0 0 1 7 0V10"/></svg></a><Suspense><LanguageSwitcher label={c.language}/></Suspense></div></header>
    <section id="top" className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 text-center"><div className="absolute left-[8%] top-[18%] h-28 w-28 rounded-full border border-[#b65f41]/30 sm:h-48 sm:w-48"/><div className="absolute bottom-[12%] right-[5%] h-48 w-32 rotate-12 rounded-[50%] bg-[#d9c7ad]/45 sm:h-72 sm:w-48"/><div className="reveal relative"><p className="eyebrow">Together · {displayDate}</p><h1 className="font-editorial my-8 text-[20vw] font-normal leading-[.72] tracking-[-.07em] sm:text-[12rem]">Ana<span className="mx-[.12em] text-[#b65f41]">+</span>Nuno</h1><p className="eyebrow">{localized('city',c.city)}</p><a href="#story" className="mt-16 inline-block text-2xl" aria-label="Scroll">↓</a></div></section>
    <section id="story" className="grid min-h-[80vh] place-items-center bg-[#392f29] px-6 py-28 text-[#f4efe7]"><div className="max-w-4xl text-center"><p className="eyebrow">01 · {lang==='pt'?'Nós':'Us'}</p><h2 className="font-editorial mt-10 text-5xl leading-tight sm:text-8xl">{localized('story',c.intro)}</h2></div></section>
    <section className="px-6 py-28 text-center sm:py-40"><p className="eyebrow">{c.countdown}</p><Countdown labels={[c.days,c.hours,c.minutes,c.seconds]} date={countdownDate}/></section>
    {(settings?.show_programme??true)&&<section id="programme" className="grid bg-[#d9c7ad] px-6 py-28 sm:grid-cols-2 sm:px-16 sm:py-40"><div><p className="eyebrow">02 · {c.programme}</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{weddingDate.split('-').reverse().join('.')}</h2></div><div className="mt-16 space-y-10 sm:mt-0">{programme.map(event=><div className="border-t border-current pt-4" key={event.id}>{event.start_time&&<span className="eyebrow">{event.start_time.slice(0,5)}{event.end_time&&` — ${event.end_time.slice(0,5)}`}</span>}<h3 className="font-editorial mt-3 text-4xl">{lang==='pt'?event.title_pt:event.title_en}</h3>{(lang==='pt'?event.description_pt:event.description_en)&&<p className="mt-2 text-lg opacity-75">{lang==='pt'?event.description_pt:event.description_en}</p>}{event.venue&&<p className="mt-2 text-lg">{event.venue}</p>}{event.address&&<p className="mt-1 text-lg opacity-65">{event.address}</p>}{event.maps_url&&<a className="eyebrow mt-4 inline-block underline" href={event.maps_url} target="_blank" rel="noreferrer">{lang==='pt'?'Ver mapa ↗':'View map ↗'}</a>}</div>)}</div></section>}
    {(settings?.show_dress_code??true)&&<section id="dress-code" className="grid min-h-[75vh] place-items-center px-6 py-28 text-center"><div className="max-w-2xl"><p className="eyebrow">03 · {c.dress}</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{localized('dress_title',c.dressTitle)}</h2><p className="mx-auto mt-8 max-w-lg leading-7 opacity-75">{localized('dress_text',c.dressText)}</p></div></section>}
    {(settings?.show_faq??true)&&<section id="faq" className="bg-[#5d6250] px-6 py-28 text-[#fffaf3] sm:px-16"><div className="mx-auto max-w-5xl"><p className="eyebrow">04 · FAQ</p><h2 className="font-editorial my-10 text-6xl sm:text-8xl">{c.faq}</h2>{(faqItems.length?faqItems:c.faqs.map(([question,answer],index)=>({id:String(index),question_pt:question,question_en:question,answer_pt:answer,answer_en:answer}))).map(item=><details className="border-t border-white/35 py-6" key={item.id}><summary className="cursor-pointer list-none font-editorial text-3xl">{lang==='pt'?item.question_pt:item.question_en}<span className="float-right">+</span></summary><p className="mt-4 max-w-xl text-lg leading-6 opacity-75">{lang==='pt'?item.answer_pt:item.answer_en}</p></details>)}</div></section>}
    <section id="rsvp" className="px-6 py-32 text-center sm:py-44"><p className="eyebrow">05 · RSVP</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{c.rsvp}</h2><p className="mt-5 text-lg opacity-70">{localized('rsvp_intro',c.rsvpText)}</p>{(settings?.rsvp_open??true)?<RsvpEntry lang={lang}/>:<p className="mt-8 text-lg">{lang==='pt'?'As respostas estão encerradas.':'Responses are now closed.'}</p>}</section>
    {(settings?.show_public_playlist??false)&&<section id="playlist" className="bg-[#d9c7ad] px-6 py-28 sm:px-16"><div className="mx-auto max-w-5xl"><p className="eyebrow">Playlist</p><h2 className="font-editorial mt-8 text-6xl sm:text-8xl">{lang==='pt'?'Sugestões para a pista':'Songs for the dance floor'}</h2>{publicPlaylist.length?(playlistDisplayMode==='cloud'?<div className="mt-14 flex flex-wrap items-baseline justify-center gap-x-8 gap-y-5 text-center">{cloudPlaylist.map(item=><div className={item.count>=4?'text-3xl':item.count===3?'text-2xl':item.count===2?'text-xl':'text-lg'} key={`${item.song}-${item.artist}`}><span className="font-editorial">{item.song}</span><span className="ml-2 text-[.65em] uppercase tracking-wider opacity-60">— {item.artist}</span>{item.count>1&&<sup className="ml-1 text-[.5em] opacity-60">×{item.count}</sup>}</div>)}</div>:<div className="mt-14 grid gap-x-12 sm:grid-cols-2">{publicPlaylist.map((item,index)=><div className="flex items-baseline justify-between gap-6 border-t border-current/30 py-5" key={`${item.song}-${item.artist}-${index}`}><h3 className="font-editorial text-2xl">{item.song}</h3><p className="text-right text-base uppercase tracking-widest opacity-65">{item.artist}</p></div>)}</div>):<p className="mt-10 text-lg opacity-70">{lang==='pt'?'Ainda não há sugestões musicais.':'There are no music suggestions yet.'}</p>}</div></section>}
    <footer className="bg-[#b65f41] px-6 py-20 text-center text-[#fffaf3]"><p className="font-editorial text-4xl sm:text-6xl">{localized('footer',c.footer)}</p><p className="eyebrow mt-10">Ana + Nuno · 2027</p><a className="mt-8 inline-block text-xs uppercase tracking-[.22em] opacity-55 transition hover:opacity-100" href="/admin">{lang==='pt'?'Acesso de administração':'Admin sign in'}</a></footer>
  </main>;
}
