"use client";
import { useEffect,useState } from "react"; import { useRouter } from "next/navigation"; import type { Guest,Invitation } from "@/types";
export function RsvpForm({code,lang}:{code:string;lang:'pt'|'en'}){const [inv,setInv]=useState<Invitation|null>(null);const [guests,setGuests]=useState<Guest[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [song,setSong]=useState('');const [artist,setArtist]=useState('');const [message,setMessage]=useState('');const router=useRouter();const pt=lang==='pt';
useEffect(()=>{fetch(`/api/rsvp?code=${encodeURIComponent(code)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setInv(d);setGuests(d.guests)}).catch(()=>setError(pt?'Não encontrámos este convite. Confirma o código.':'We could not find this invitation. Check the code.')).finally(()=>setLoading(false))},[code,pt]);
const update=(i:number,key:keyof Guest,value:string)=>setGuests(x=>x.map((g,n)=>n===i?{...g,[key]:value}:g));
if(loading)return <p className="py-20 text-center eyebrow">{pt?'A abrir o convite…':'Opening your invitation…'}</p>;if(error)return <div className="py-20 text-center"><p>{error}</p><a href={`/?lang=${lang}#rsvp`} className="button mt-8">{pt?'Voltar':'Go back'}</a></div>;
return <form className="mx-auto max-w-3xl" onSubmit={async e=>{e.preventDefault();setError('');const r=await fetch('/api/rsvp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,guests,song,artist,message})});if(r.ok)router.push(`/thank-you?lang=${lang}`);else setError(pt?'Não foi possível guardar. Tenta novamente.':'We could not save your reply. Try again.')}}><div className="mb-16 text-center"><p className="eyebrow">{pt?'O vosso convite':'Your invitation'}</p><h1 className="font-editorial mt-6 text-6xl">{inv?.guests.map(g=>g.name).join(' & ')}</h1></div>
<div className="space-y-7">{guests.map((g,i)=><fieldset className="border-t border-[#392f29]/30 pt-6" key={g.id}><legend className="font-editorial text-3xl">{g.name}</legend><div className="mt-5 flex gap-6"><label><input type="radio" name={`attendance-${g.id}`} checked={g.attendance==='accepted'} onChange={()=>update(i,'attendance','accepted')}/> <span className="ml-2">{pt?'Aceito':'Accept'}</span></label><label><input type="radio" name={`attendance-${g.id}`} checked={g.attendance==='declined'} onChange={()=>update(i,'attendance','declined')}/> <span className="ml-2">{pt?'Não poderei ir':'Decline'}</span></label></div>{g.attendance==='accepted'&&<input className="field mt-4" value={g.dietary_restrictions??''} onChange={e=>update(i,'dietary_restrictions',e.target.value)} placeholder={pt?'Restrições alimentares (opcional)':'Dietary restrictions (optional)'}/>}</fieldset>)}</div>
<section className="mt-20"><p className="eyebrow">Playlist</p><h2 className="font-editorial mt-4 text-4xl">{pt?'Uma música para a pista':'One for the dance floor'}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><input className="field" value={song} onChange={e=>setSong(e.target.value)} placeholder={pt?'Música':'Song'}/><input className="field" value={artist} onChange={e=>setArtist(e.target.value)} placeholder={pt?'Artista':'Artist'}/></div></section>
<section className="mt-16"><label className="eyebrow" htmlFor="message">{pt?'Uma mensagem para nós':'A message for us'}</label><textarea id="message" className="field mt-4 min-h-28 resize-y" maxLength={500} value={message} onChange={e=>setMessage(e.target.value)} /></section>{error&&<p className="mt-6 text-sm text-red-800" role="alert">{error}</p>}<button className="button mt-10" type="submit" disabled={guests.some(g=>g.attendance==='pending')}>{pt?'Enviar resposta':'Send reply'}</button></form>}
