"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import type { Guest,Invitation,RsvpAnswer,RsvpQuestion } from "@/types";

type Content={playlist_prompt_pt:string;playlist_prompt_en:string;message_prompt_pt:string;message_prompt_en:string};
const answerKey=(questionId:string,guestId:string|null)=>`${questionId}:${guestId??'invitation'}`;
const emptyAnswer=(value:string|string[]|boolean|undefined)=>value===undefined||value===''||(Array.isArray(value)&&value.length===0);

function QuestionField({question,guestId,lang,value,onChange}:{question:RsvpQuestion;guestId:string|null;lang:'pt'|'en';value:string|string[]|boolean|undefined;onChange:(value:string|string[]|boolean)=>void}){
  const pt=lang==='pt';const label=pt?question.label_pt:question.label_en;const help=pt?question.help_pt:question.help_en;const options=question.options??[];const name=answerKey(question.id,guestId);
  return <fieldset className="border-t border-[#392f29]/20 pt-5"><legend className="font-editorial text-2xl">{label}{question.required&&<span className="ml-1 text-[#b65f41]">*</span>}</legend>{help&&<p className="mt-2 text-lg opacity-65">{help}</p>}<div className="mt-4">
    {question.question_type==='short_text'&&<input className="field" value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)} required={question.required}/>}
    {question.question_type==='long_text'&&<textarea className="field min-h-28" value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)} required={question.required}/>}
    {question.question_type==='yes_no'&&<div className="flex gap-6"><label><input type="radio" name={name} checked={value===true} onChange={()=>onChange(true)} required={question.required}/> {pt?'Sim':'Yes'}</label><label><input type="radio" name={name} checked={value===false} onChange={()=>onChange(false)}/> {pt?'Não':'No'}</label></div>}
    {question.question_type==='single_choice'&&<div className="grid gap-3">{options.map(option=><label key={option.value}><input type="radio" name={name} checked={value===option.value} onChange={()=>onChange(option.value)} required={question.required}/> {pt?option.label_pt:option.label_en}</label>)}</div>}
    {question.question_type==='multiple_choice'&&<div className="grid gap-3">{options.map(option=>{const selected=Array.isArray(value)?value:[];return <label key={option.value}><input type="checkbox" checked={selected.includes(option.value)} onChange={e=>onChange(e.target.checked?[...selected,option.value]:selected.filter(x=>x!==option.value))}/> {pt?option.label_pt:option.label_en}</label>})}</div>}
  </div></fieldset>;
}

export function RsvpForm({code,lang,content,showPlaylist}:{code:string;lang:'pt'|'en';content:Content;showPlaylist:boolean}){
  const [inv,setInv]=useState<Invitation|null>(null);const [guests,setGuests]=useState<Guest[]>([]);const [answers,setAnswers]=useState<Record<string,string|string[]|boolean>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [song,setSong]=useState('');const [artist,setArtist]=useState('');const [message,setMessage]=useState('');const router=useRouter();const pt=lang==='pt';
  useEffect(()=>{fetch(`/api/rsvp?code=${encodeURIComponent(code)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setInv(d);setGuests(d.guests);setAnswers(Object.fromEntries((d.answers??[]).map((a:RsvpAnswer)=>[answerKey(a.question_id,a.guest_id),a.answer]))) }).catch(()=>setError(pt?'Não encontrámos este convite. Confirma o código.':'We could not find this invitation. Check the code.')).finally(()=>setLoading(false))},[code,pt]);
  const update=(i:number,key:keyof Guest,value:string)=>setGuests(x=>x.map((g,n)=>n===i?{...g,[key]:value}:g));
  const setAnswer=(questionId:string,guestId:string|null,value:string|string[]|boolean)=>setAnswers(current=>({...current,[answerKey(questionId,guestId)]:value}));
  if(loading)return <p className="py-20 text-center eyebrow">{pt?'A abrir o convite…':'Opening your invitation…'}</p>;if(error)return <div className="py-20 text-center"><p>{error}</p><a href={`/?lang=${lang}#rsvp`} className="button mt-8">{pt?'Voltar':'Go back'}</a></div>;
  const invitationQuestions=inv?.questions.filter(q=>q.scope==='invitation')??[];const guestQuestions=inv?.questions.filter(q=>q.scope==='guest')??[];
  return <form className="mx-auto max-w-3xl" onSubmit={async e=>{e.preventDefault();setError('');const questionAnswers:RsvpAnswer[]=[];let missing=false;(inv?.questions??[]).forEach(q=>{const targets=q.scope==='guest'?guests.filter(g=>g.attendance==='accepted').map(g=>g.id):[null];targets.forEach(guestId=>{const answer=answers[answerKey(q.id,guestId)];if(q.required&&emptyAnswer(answer))missing=true;if(!emptyAnswer(answer))questionAnswers.push({question_id:q.id,guest_id:guestId,answer:answer as string|string[]|boolean})})});if(missing){setError(pt?'Responde a todas as perguntas obrigatórias.':'Please answer every required question.');return}const r=await fetch('/api/rsvp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,guests,song,artist,message,questionAnswers})});if(r.ok)router.push(`/thank-you?lang=${lang}`);else setError(pt?'Não foi possível guardar. Verifica os campos obrigatórios e tenta novamente.':'We could not save your reply. Check the required fields and try again.')}}>
    <div className="mb-16 text-center"><p className="eyebrow">{pt?'O vosso convite':'Your invitation'}</p><h1 className="font-editorial mt-6 text-6xl">{inv?.guests.map(g=>g.name).join(' & ')}</h1></div>
    <div className="space-y-10">{guests.map((g,i)=><fieldset className="border-t border-[#392f29]/30 pt-6" key={g.id}><legend className="font-editorial text-3xl">{g.name}</legend><div className="mt-5 flex gap-6"><label><input type="radio" name={`attendance-${g.id}`} checked={g.attendance==='accepted'} onChange={()=>update(i,'attendance','accepted')} required/> <span className="ml-2">{pt?'Aceito':'Accept'}</span></label><label><input type="radio" name={`attendance-${g.id}`} checked={g.attendance==='declined'} onChange={()=>update(i,'attendance','declined')}/> <span className="ml-2">{pt?'Não poderei ir':'Decline'}</span></label></div>{g.attendance==='accepted'&&<><input className="field mt-4" value={g.dietary_restrictions??''} onChange={e=>update(i,'dietary_restrictions',e.target.value)} placeholder={pt?'Restrições alimentares (opcional)':'Dietary restrictions (optional)'}/>{guestQuestions.length>0&&<div className="mt-8 space-y-7">{guestQuestions.map(q=><QuestionField key={q.id} question={q} guestId={g.id} lang={lang} value={answers[answerKey(q.id,g.id)]} onChange={v=>setAnswer(q.id,g.id,v)}/>)}</div>}</>}</fieldset>)}</div>
    {invitationQuestions.length>0&&<section className="mt-20 space-y-7"><p className="eyebrow">{pt?'Algumas perguntas':'A few questions'}</p>{invitationQuestions.map(q=><QuestionField key={q.id} question={q} guestId={null} lang={lang} value={answers[answerKey(q.id,null)]} onChange={v=>setAnswer(q.id,null,v)}/>)}</section>}
    {showPlaylist&&<section className="mt-20"><p className="eyebrow">Playlist</p><h2 className="font-editorial mt-4 text-4xl">{pt?content.playlist_prompt_pt:content.playlist_prompt_en}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><input className="field" value={song} onChange={e=>setSong(e.target.value)} placeholder={pt?'Música':'Song'}/><input className="field" value={artist} onChange={e=>setArtist(e.target.value)} placeholder={pt?'Artista':'Artist'}/></div></section>}
    <section className="mt-16"><label className="eyebrow" htmlFor="message">{pt?content.message_prompt_pt:content.message_prompt_en}</label><textarea id="message" className="field mt-4 min-h-28 resize-y" maxLength={500} value={message} onChange={e=>setMessage(e.target.value)} /></section>{error&&<p className="mt-6 text-lg text-red-800" role="alert">{error}</p>}<button className="button mt-10" type="submit" disabled={guests.some(g=>g.attendance==='pending')}>{pt?'Enviar resposta':'Send reply'}</button>
  </form>;
}
