"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import type { Guest,Invitation,RsvpAnswer,RsvpQuestion } from "@/types";
import { getUiCopy,type UiCopy } from "@/lib/ui-copy";

type Content={playlist_prompt_pt:string;playlist_prompt_en:string;message_prompt_pt:string;message_prompt_en:string;ui_copy?:UiCopy};
type SongSuggestion={song:string;artist:string};
const answerKey=(questionId:string,guestId:string|null)=>`${questionId}:${guestId??'invitation'}`;
const emptyAnswer=(value:string|string[]|boolean|undefined)=>value===undefined||value===''||(Array.isArray(value)&&value.length===0);

function QuestionField({question,guestId,lang,value,onChange,yesLabel,noLabel}:{question:RsvpQuestion;guestId:string|null;lang:'pt'|'en';value:string|string[]|boolean|undefined;onChange:(value:string|string[]|boolean)=>void;yesLabel:string;noLabel:string}){
  const pt=lang==='pt';const label=pt?question.label_pt:question.label_en;const help=pt?question.help_pt:question.help_en;const options=question.options??[];const name=answerKey(question.id,guestId);
  return <fieldset className="border-t border-[#392f29]/20 pt-5"><legend className="font-editorial text-2xl">{label}{question.required&&<span className="ml-1 text-[#b65f41]">*</span>}</legend>{help&&<p className="mt-2 text-lg opacity-65">{help}</p>}<div className="mt-4">
    {question.question_type==='short_text'&&<input className="field" value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)} required={question.required}/>}
    {question.question_type==='long_text'&&<textarea className="field min-h-28" value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)} required={question.required}/>}
    {question.question_type==='yes_no'&&<div className="flex gap-6"><label><input type="radio" name={name} checked={value===true} onChange={()=>onChange(true)} required={question.required}/> {yesLabel}</label><label><input type="radio" name={name} checked={value===false} onChange={()=>onChange(false)}/> {noLabel}</label></div>}
    {question.question_type==='single_choice'&&<div className="grid gap-3">{options.map(option=><label key={option.value}><input type="radio" name={name} checked={value===option.value} onChange={()=>onChange(option.value)} required={question.required}/> {pt?option.label_pt:option.label_en}</label>)}</div>}
    {question.question_type==='multiple_choice'&&<div className="grid gap-3">{options.map(option=>{const selected=Array.isArray(value)?value:[];return <label key={option.value}><input type="checkbox" checked={selected.includes(option.value)} onChange={e=>onChange(e.target.checked?[...selected,option.value]:selected.filter(x=>x!==option.value))}/> {pt?option.label_pt:option.label_en}</label>})}</div>}
  </div></fieldset>;
}

export function RsvpForm({code,lang,content,showPlaylist}:{code:string;lang:'pt'|'en';content:Content;showPlaylist:boolean}){
  const [inv,setInv]=useState<Invitation|null>(null);const [guests,setGuests]=useState<Guest[]>([]);const [answers,setAnswers]=useState<Record<string,string|string[]|boolean>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [songs,setSongs]=useState<SongSuggestion[]>([{song:'',artist:''}]);const [message,setMessage]=useState('');const router=useRouter();const pt=lang==='pt';const ui=(key:string)=>getUiCopy(content.ui_copy,key,lang);
  useEffect(()=>{fetch(`/api/rsvp?code=${encodeURIComponent(code)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setInv(d);setGuests(d.guests);setAnswers(Object.fromEntries((d.answers??[]).map((a:RsvpAnswer)=>[answerKey(a.question_id,a.guest_id),a.answer]))) }).catch(()=>setError(getUiCopy(content.ui_copy,'invalid_invitation',lang))).finally(()=>setLoading(false))},[code,lang,content.ui_copy]);
  const update=(i:number,key:keyof Guest,value:string)=>setGuests(x=>x.map((g,n)=>n===i?{...g,[key]:value}:g));
  const updateSong=(i:number,key:keyof SongSuggestion,value:string)=>setSongs(current=>current.map((song,index)=>index===i?{...song,[key]:value}:song));
  const setAnswer=(questionId:string,guestId:string|null,value:string|string[]|boolean)=>setAnswers(current=>({...current,[answerKey(questionId,guestId)]:value}));
  if(loading)return <p className="py-20 text-center eyebrow">{ui('opening_invitation')}</p>;if(error)return <div className="py-20 text-center"><p>{error}</p><a href={`/?lang=${lang}#rsvp`} className="button mt-8">{ui('go_back_button')}</a></div>;
  const invitationQuestions=inv?.questions.filter(q=>q.scope==='invitation')??[];const guestQuestions=inv?.questions.filter(q=>q.scope==='guest')??[];const isPreEvent=inv?.event_type==='pre_event';
  return <form className="mx-auto max-w-3xl" onSubmit={async e=>{e.preventDefault();setError('');const questionAnswers:RsvpAnswer[]=[];let missing=false;(inv?.questions??[]).forEach(q=>{const targets=q.scope==='guest'?guests.filter(g=>g.attendance==='accepted').map(g=>g.id):[null];targets.forEach(guestId=>{const answer=answers[answerKey(q.id,guestId)];if(q.required&&emptyAnswer(answer))missing=true;if(!emptyAnswer(answer))questionAnswers.push({question_id:q.id,guest_id:guestId,answer:answer as string|string[]|boolean})})});if(missing){setError(ui('required_error'));return}const musicSuggestions=songs.filter(item=>item.song.trim()&&item.artist.trim());const r=await fetch('/api/rsvp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,guests,musicSuggestions,message,questionAnswers})});if(r.ok)router.push(`/thank-you?lang=${lang}&event=${inv?.event_type??'wedding'}`);else setError(ui('save_error'))}}>
    <div className="mb-16 text-center"><p className="eyebrow">{ui('invitation_heading')}</p><h1 className="font-editorial mt-6 text-6xl">{inv?.guests.map(g=>g.name).join(' + ')}</h1></div>
    <div className="space-y-10">{guests.map((g,i)=><fieldset className="border-t border-[#392f29]/30 pt-6" key={g.id}><legend className="font-editorial text-3xl">{g.name}</legend><div className="mt-5 flex gap-6"><label><input type="radio" name={`attendance-${g.id}`} checked={g.attendance==='accepted'} onChange={()=>update(i,'attendance','accepted')} required/> <span className="ml-2">{ui('accept_label')}</span></label><label><input type="radio" name={`attendance-${g.id}`} checked={g.attendance==='declined'} onChange={()=>update(i,'attendance','declined')}/> <span className="ml-2">{ui('decline_label')}</span></label></div>{g.attendance==='accepted'&&<><input className="field mt-4" value={g.dietary_restrictions??''} onChange={e=>update(i,'dietary_restrictions',e.target.value)} placeholder={ui('dietary_placeholder')}/>{guestQuestions.length>0&&<div className="mt-8 space-y-7">{guestQuestions.map(q=><QuestionField key={q.id} question={q} guestId={g.id} lang={lang} value={answers[answerKey(q.id,g.id)]} onChange={v=>setAnswer(q.id,g.id,v)} yesLabel={ui('yes_label')} noLabel={ui('no_label')}/>)}</div>}</>}</fieldset>)}</div>
    {invitationQuestions.length>0&&<section className="mt-20 space-y-7"><p className="eyebrow">{ui('questions_heading')}</p>{invitationQuestions.map(q=><QuestionField key={q.id} question={q} guestId={null} lang={lang} value={answers[answerKey(q.id,null)]} onChange={v=>setAnswer(q.id,null,v)} yesLabel={ui('yes_label')} noLabel={ui('no_label')}/>)}</section>}
    {showPlaylist&&!isPreEvent&&<section className="mt-20"><p className="eyebrow">{getUiCopy(content.ui_copy,'playlist_section_label',lang)}</p><h2 className="font-editorial mt-4 text-4xl">{pt?content.playlist_prompt_pt:content.playlist_prompt_en}</h2><div className="mt-5 space-y-6">{songs.map((item,index)=><fieldset className="grid gap-5 border-t border-[#392f29]/20 pt-4 sm:grid-cols-2" key={index}><legend className="eyebrow">{ui('suggestion_label')} {index+1}</legend><input className="field" value={item.song} onChange={e=>updateSong(index,'song',e.target.value)} placeholder={ui('song_placeholder')}/><input className="field" value={item.artist} onChange={e=>updateSong(index,'artist',e.target.value)} placeholder={ui('artist_placeholder')}/>{songs.length>1&&<button className="justify-self-start text-base uppercase tracking-widest underline sm:col-span-2" type="button" onClick={()=>setSongs(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>{ui('remove_suggestion')}</button>}</fieldset>)}</div><button className="button mt-7" type="button" onClick={()=>setSongs(current=>[...current,{song:'',artist:''}])}>{ui('add_song_button')}</button></section>}
    <section className="mt-16"><label className="eyebrow" htmlFor="message">{pt?content.message_prompt_pt:content.message_prompt_en}</label><textarea id="message" className="field mt-4 min-h-28 resize-y" maxLength={500} value={message} onChange={e=>setMessage(e.target.value)} /></section>{error&&<p className="mt-6 text-lg text-red-800" role="alert">{error}</p>}<button className="button mt-10" type="submit" disabled={guests.some(g=>g.attendance==='pending')}>{ui('send_reply_button')}</button>
  </form>;
}
