export type UiCopy=Record<string,string>;

export const uiCopyFields=[
  ['couple_name','Couple name','Nome do casal'],['header_monogram','Header monogram','Monograma do header'],['hero_kicker','Hero label','Etiqueta inicial'],
  ['story_nav','Story menu name','Nome História no menu'],['story_section_label','Story section label','Etiqueta da secção História'],
  ['countdown_label','Countdown title','Título da contagem decrescente'],['days_label','Days label','Etiqueta dias'],['hours_label','Hours label','Etiqueta horas'],['minutes_label','Minutes label','Etiqueta minutos'],['seconds_label','Seconds label','Etiqueta segundos'],
  ['programme_nav','Programme menu name','Nome Programa no menu'],['programme_section_label','Programme section label','Etiqueta da secção Programa'],['map_link','Map link','Ligação para o mapa'],
  ['dress_nav','Dress-code menu name','Nome Dress code no menu'],['dress_section_label','Dress-code section label','Etiqueta da secção Dress code'],
  ['faq_nav','FAQ menu name','Nome FAQ no menu'],['faq_section_label','FAQ section label','Etiqueta da secção FAQ'],['faq_title','FAQ title','Título da FAQ'],
  ['rsvp_nav','RSVP menu name','Nome RSVP no menu'],['rsvp_section_label','RSVP section label','Etiqueta da secção RSVP'],['rsvp_title','RSVP title','Título do RSVP'],['rsvp_closed','Wedding RSVP closed message','Mensagem de RSVP encerrado'],
  ['playlist_nav','Music menu name','Nome Música no menu'],['playlist_section_label','Music section label','Etiqueta da secção Música'],['playlist_title','Music section title','Título da secção Música'],['playlist_empty','Empty music list message','Mensagem de lista musical vazia'],
  ['pre_event_nav','Registry-office RSVP menu name','Nome RSVP Cartório no menu'],['pre_event_section_label','Registry-office section label','Etiqueta da secção Cartório'],['pre_event_when_label','When label','Etiqueta Quando'],['pre_event_where_label','Where label','Etiqueta Onde'],['pre_event_rsvp_label','Registry-office RSVP label','Etiqueta RSVP do Cartório'],['pre_event_closed','Registry-office RSVP closed message','Mensagem de RSVP do Cartório encerrado'],
  ['footer_brand','Footer signature','Assinatura do rodapé'],['admin_sign_in','Admin link','Ligação de administração'],
  ['invitation_code_label','Invitation-code field','Campo de código do convite'],['code_error','Invalid-code message','Mensagem de código inválido'],['continue_button','Continue button','Botão Continuar'],
  ['back_brand','Back-to-site link','Ligação para voltar ao site'],['missing_code_title','Missing-code title','Título de código em falta'],['enter_code_button','Enter-code button','Botão Introduzir código'],
  ['opening_invitation','Opening invitation message','Mensagem a abrir convite'],['invalid_invitation','Invitation-not-found message','Mensagem de convite não encontrado'],['go_back_button','Go-back button','Botão Voltar'],['invitation_heading','Invitation heading','Título do convite'],
  ['accept_label','Accept option','Opção Aceito'],['decline_label','Decline option','Opção Recusar'],['dietary_placeholder','Dietary field','Campo de restrições alimentares'],['questions_heading','Questions heading','Título das perguntas'],['yes_label','Yes option','Opção Sim'],['no_label','No option','Opção Não'],
  ['suggestion_label','Suggestion label','Etiqueta Sugestão'],['song_placeholder','Song field','Campo Música'],['artist_placeholder','Artist field','Campo Artista'],['remove_suggestion','Remove-song button','Botão Remover música'],['add_song_button','Add-song button','Botão Adicionar música'],
  ['required_error','Required-fields error','Erro de campos obrigatórios'],['save_error','Save error','Erro ao guardar'],['send_reply_button','Submit RSVP button','Botão Enviar RSVP'],
  ['thank_you_title','Thank-you title','Título de agradecimento'],['thank_you_message','Thank-you message','Mensagem de agradecimento'],['back_home_button','Back-home button','Botão Voltar ao início']
] as const;

export const fallbackUiCopy:Record<string,{pt:string;en:string}>={
  couple_name:{pt:'Ana + Nuno',en:'Ana + Nuno'},header_monogram:{pt:'A + N',en:'A + N'},hero_kicker:{pt:'Together',en:'Together'},
  story_nav:{pt:'História',en:'Story'},story_section_label:{pt:'01 · Nós',en:'01 · Us'},countdown_label:{pt:'Até estarmos juntos',en:'Until we are together'},days_label:{pt:'dias',en:'days'},hours_label:{pt:'horas',en:'hours'},minutes_label:{pt:'minutos',en:'minutes'},seconds_label:{pt:'segundos',en:'seconds'},
  programme_nav:{pt:'Programa',en:'Programme'},programme_section_label:{pt:'02 · O dia',en:'02 · The day'},map_link:{pt:'Ver mapa ↗',en:'View map ↗'},dress_nav:{pt:'Dress code',en:'Dress code'},dress_section_label:{pt:'03 · Código de vestuário',en:'03 · Dress code'},faq_nav:{pt:'FAQ',en:'FAQ'},faq_section_label:{pt:'04 · FAQ',en:'04 · FAQ'},faq_title:{pt:'Algumas notas',en:'A few notes'},
  rsvp_nav:{pt:'RSVP',en:'RSVP'},rsvp_section_label:{pt:'05 · RSVP',en:'05 · RSVP'},rsvp_title:{pt:'Confirmar presença',en:'RSVP'},rsvp_closed:{pt:'As respostas estão encerradas.',en:'Responses are now closed.'},playlist_nav:{pt:'Música',en:'Music'},playlist_section_label:{pt:'Música',en:'Playlist'},playlist_title:{pt:'Sugestões para a pista',en:'Songs for the dance floor'},playlist_empty:{pt:'Ainda não há sugestões musicais.',en:'There are no music suggestions yet.'},
  pre_event_nav:{pt:'RSVP Cartório',en:'Registry office RSVP'},pre_event_section_label:{pt:'Cartório',en:'Registry office'},pre_event_when_label:{pt:'Quando',en:'When'},pre_event_where_label:{pt:'Onde',en:'Where'},pre_event_rsvp_label:{pt:'RSVP · 18.10.2026',en:'RSVP · 18.10.2026'},pre_event_closed:{pt:'As respostas do pré-evento estão encerradas.',en:'Pre-event responses are now closed.'},footer_brand:{pt:'Ana + Nuno',en:'Ana + Nuno'},admin_sign_in:{pt:'Acesso de administração',en:'Admin sign in'},
  invitation_code_label:{pt:'Código do convite',en:'Invitation code'},code_error:{pt:'Confirma o código e tenta novamente.',en:'Check the code and try again.'},continue_button:{pt:'Continuar',en:'Continue'},back_brand:{pt:'← Ana + Nuno',en:'← Ana + Nuno'},missing_code_title:{pt:'Falta o código',en:'Invitation code needed'},enter_code_button:{pt:'Introduzir código',en:'Enter code'},opening_invitation:{pt:'A abrir o convite…',en:'Opening your invitation…'},invalid_invitation:{pt:'Não encontrámos este convite. Confirma o código.',en:'We could not find this invitation. Check the code.'},go_back_button:{pt:'Voltar',en:'Go back'},invitation_heading:{pt:'O vosso convite',en:'Your invitation'},
  accept_label:{pt:'Aceito',en:'Accept'},decline_label:{pt:'Não poderei ir',en:'Decline'},dietary_placeholder:{pt:'Restrições alimentares (opcional)',en:'Dietary restrictions (optional)'},questions_heading:{pt:'Algumas perguntas',en:'A few questions'},yes_label:{pt:'Sim',en:'Yes'},no_label:{pt:'Não',en:'No'},suggestion_label:{pt:'Sugestão',en:'Suggestion'},song_placeholder:{pt:'Música',en:'Song'},artist_placeholder:{pt:'Artista',en:'Artist'},remove_suggestion:{pt:'Remover sugestão',en:'Remove suggestion'},add_song_button:{pt:'Adicionar outra música +',en:'Add another song +'},required_error:{pt:'Responde a todas as perguntas obrigatórias.',en:'Please answer every required question.'},save_error:{pt:'Não foi possível guardar. Verifica os campos obrigatórios e tenta novamente.',en:'We could not save your reply. Check the required fields and try again.'},send_reply_button:{pt:'Enviar resposta',en:'Send reply'},thank_you_title:{pt:'Obrigado',en:'Thank you'},thank_you_message:{pt:'A tua resposta já está connosco.',en:'Your reply is safely with us.'},back_home_button:{pt:'Voltar ao início',en:'Back home'}
};

export const getUiCopy=(uiCopy:UiCopy|undefined,key:string,lang:'pt'|'en')=>uiCopy?.[`${key}_${lang}`]||fallbackUiCopy[key]?.[lang]||key;
