"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function AdminSetup(){
  const [ready,setReady]=useState(false);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const router=useRouter();
  useEffect(()=>{const supabase=createClient();const initialize=async()=>{const hash=new URLSearchParams(window.location.hash.slice(1));const accessToken=hash.get('access_token');const refreshToken=hash.get('refresh_token');const callbackError=hash.get('error_description');let {data:{session}}=await supabase.auth.getSession();if(!session&&accessToken&&refreshToken){const result=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});session=result.data.session;if(result.error)setError('This password link is invalid or has expired.')}const code=new URLSearchParams(window.location.search).get('code');if(!session&&code){const result=await supabase.auth.exchangeCodeForSession(code);session=result.data.session;if(result.error)setError('This password link is invalid or has expired.')}if(session)window.history.replaceState({},'',window.location.pathname);if(!session)setError(callbackError?decodeURIComponent(callbackError.replace(/\+/g,' ')):'Open this page using the newest password email link.');setReady(Boolean(session))};void initialize()},[]);
  return <main className="grid min-h-screen place-items-center px-6"><form className="w-full max-w-sm" onSubmit={async event=>{event.preventDefault();setError('');const form=new FormData(event.currentTarget);const password=String(form.get('password')||'');const confirmation=String(form.get('confirmation')||'');if(password.length<10){setError('Use at least 10 characters.');return}if(password!==confirmation){setError('The passwords do not match.');return}setSaving(true);const {error:updateError}=await createClient().auth.updateUser({password});if(updateError){setError(updateError.message);setSaving(false);return}router.push('/admin');router.refresh()}}><p className="eyebrow">Together 2027</p><h1 className="font-editorial mt-5 text-6xl">Create password</h1><p className="mt-5 text-sm leading-6 opacity-70">Choose the password you will use for the wedding back office.</p><label className="mt-10 block text-xs uppercase tracking-wider" htmlFor="password">Password</label><input className="field" id="password" name="password" type="password" minLength={10} autoComplete="new-password" required disabled={!ready||Boolean(error)}/><label className="mt-6 block text-xs uppercase tracking-wider" htmlFor="confirmation">Confirm password</label><input className="field" id="confirmation" name="confirmation" type="password" minLength={10} autoComplete="new-password" required disabled={!ready||Boolean(error)}/>{!ready&&<p className="mt-5 text-sm">Validating invitation…</p>}{error&&<p className="mt-5 text-sm text-red-800" role="alert">{error}</p>}<button className="button mt-8 w-full" disabled={!ready||Boolean(error)||saving}>{saving?'Saving…':'Create password'}</button></form></main>;
}
