create extension if not exists pgcrypto;
create table if not exists public.invitations (id uuid primary key default gen_random_uuid(), code text unique not null, language text not null default 'pt' check(language in('pt','en')), max_guests integer not null default 1 check(max_guests between 1 and 4), status text not null default 'active' check(status in('active','used','disabled')), created_at timestamptz not null default now());
alter table public.invitations add column if not exists language text not null default 'pt' check(language in('pt','en'));
alter table public.invitations add column if not exists max_guests integer not null default 1 check(max_guests between 1 and 4);
alter table public.invitations add column if not exists status text not null default 'active' check(status in('active','used','disabled'));
alter table public.invitations add column if not exists created_at timestamptz not null default now();
create table if not exists public.guests (id uuid primary key default gen_random_uuid(), invitation_id uuid not null references public.invitations(id) on delete cascade, name text not null, category text not null default 'adult' check(category in('adult','child','baby')), attendance text not null default 'pending' check(attendance in('pending','accepted','declined')), dietary_restrictions text, notes text, updated_at timestamptz not null default now());
alter table public.guests add column if not exists category text not null default 'adult' check(category in('adult','child','baby'));
alter table public.guests add column if not exists attendance text not null default 'pending' check(attendance in('pending','accepted','declined'));
alter table public.guests add column if not exists dietary_restrictions text;
alter table public.guests add column if not exists notes text;
alter table public.guests add column if not exists updated_at timestamptz not null default now();
create table if not exists public.music_suggestions (id uuid primary key default gen_random_uuid(), invitation_id uuid references public.invitations(id) on delete set null, song text not null, artist text not null, created_at timestamptz not null default now());
alter table public.music_suggestions add column if not exists invitation_id uuid references public.invitations(id) on delete set null;
alter table public.music_suggestions add column if not exists song text;
alter table public.music_suggestions add column if not exists artist text;
alter table public.music_suggestions add column if not exists created_at timestamptz not null default now();
create table if not exists public.messages (id uuid primary key default gen_random_uuid(), invitation_id uuid references public.invitations(id) on delete set null, message text not null check(char_length(message)<=500), created_at timestamptz not null default now());
create table if not exists public.wedding_settings (id smallint primary key default 1 check(id=1), rsvp_open boolean not null default true, rsvp_deadline date not null default '2027-01-24', show_faq boolean not null default true, show_dress_code boolean not null default true, show_playlist boolean not null default true, show_programme boolean not null default true, updated_at timestamptz not null default now());
insert into public.wedding_settings(id) values(1) on conflict do nothing;
update public.invitations i set max_guests=least(4,g.guest_count) from (select invitation_id,count(*)::integer guest_count from public.guests group by invitation_id) g where i.id=g.invitation_id and i.max_guests<g.guest_count;
do $$ begin
  if exists(select 1 from information_schema.columns where table_schema='public' and table_name='guests' and column_name='confirmed' and data_type='boolean') then
    execute 'update public.guests set attendance=case when confirmed then ''accepted'' when confirmed=false then ''declined'' else ''pending'' end where confirmed is not null';
  elsif exists(select 1 from information_schema.columns where table_schema='public' and table_name='guests' and column_name='attending' and data_type='boolean') then
    execute 'update public.guests set attendance=case when attending then ''accepted'' when attending=false then ''declined'' else ''pending'' end where attending is not null';
  end if;
end $$;
alter table public.invitations enable row level security; alter table public.guests enable row level security; alter table public.music_suggestions enable row level security; alter table public.messages enable row level security; alter table public.wedding_settings enable row level security;
create policy "admins invitations" on public.invitations for all to authenticated using(true) with check(true); create policy "admins guests" on public.guests for all to authenticated using(true) with check(true); create policy "admins music" on public.music_suggestions for all to authenticated using(true) with check(true); create policy "admins messages" on public.messages for all to authenticated using(true) with check(true); create policy "admins settings" on public.wedding_settings for all to authenticated using(true) with check(true);
create policy "public settings" on public.wedding_settings for select to anon using(true);
create or replace function public.lookup_invitation(invitation_code text) returns jsonb language plpgsql security definer set search_path=public as $$ declare result jsonb; begin if not coalesce((select rsvp_open from wedding_settings where id=1),true) then raise exception 'RSVP closed';end if;select jsonb_build_object('id',i.id,'code',i.code,'language',i.language,'max_guests',i.max_guests,'status',i.status,'guests',coalesce(jsonb_agg(jsonb_build_object('id',g.id,'name',g.name,'category',g.category,'attendance',g.attendance,'dietary_restrictions',g.dietary_restrictions,'notes',g.notes) order by g.name) filter(where g.id is not null),'[]'::jsonb)) into result from invitations i left join guests g on g.invitation_id=i.id where upper(i.code)=upper(invitation_code) and i.status<>'disabled' group by i.id; return result; end $$;
grant execute on function public.lookup_invitation(text) to anon,authenticated;
create or replace function public.submit_invitation_response(invitation_code text,guest_responses jsonb,song_title text default null,song_artist text default null,couple_message text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare inv invitations%rowtype; item jsonb; begin if not coalesce((select rsvp_open and current_date<=rsvp_deadline from wedding_settings where id=1),true) then raise exception 'RSVP closed';end if;select * into inv from invitations where upper(code)=upper(invitation_code) and status<>'disabled' for update;if inv.id is null then raise exception 'Invitation not found';end if;if jsonb_array_length(guest_responses)>inv.max_guests then raise exception 'Too many guests';end if;for item in select * from jsonb_array_elements(guest_responses) loop update guests set attendance=case when item->>'attendance' in('accepted','declined') then item->>'attendance' else attendance end,dietary_restrictions=nullif(left(item->>'dietary_restrictions',500),''),updated_at=now() where id=(item->>'id')::uuid and invitation_id=inv.id;end loop;if nullif(trim(song_title),'') is not null and nullif(trim(song_artist),'') is not null then insert into music_suggestions(invitation_id,song,artist) values(inv.id,left(trim(song_title),150),left(trim(song_artist),150));end if;if nullif(trim(couple_message),'') is not null then insert into messages(invitation_id,message) values(inv.id,left(trim(couple_message),500));end if;update invitations set status='used' where id=inv.id;return inv.id;end $$;
grant execute on function public.submit_invitation_response(text,jsonb,text,text,text) to anon,authenticated;
insert into public.invitations(code,language,max_guests,status) values('ANA-NUNO-2027-TEST','pt',2,'active') on conflict(code) do nothing;
insert into public.guests(invitation_id,name) select i.id,n from public.invitations i cross join (values('Ana Garcia'),('Nuno Fernandes')) as names(n) where i.code='ANA-NUNO-2027-TEST' and not exists(select 1 from public.guests g where g.invitation_id=i.id);
